apiVersion: apps/v1
kind: Deployment
metadata:
  name: koala-restaurant
  labels:
    app: koala-restaurant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: koala-restaurant
  template:
    metadata:
      labels:
        app: koala-restaurant
    spec:
      containers:
        - name: koala-restaurant
          image: anisphia/koala-restaurant:latest
          ports:
            - containerPort: 3000
